// This file contains model definitions for built-in providers.
// Adapted from pi-mono models.generated.ts - only anthropic, openai, google providers.

export const MODELS = {
	"anthropic": {
		"claude-haiku-4-5": {
			id: "claude-haiku-4-5",
			name: "Claude Haiku 4.5 (latest)",
			api: "anthropic-messages",
			provider: "anthropic",
			baseUrl: "https://api.anthropic.com",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 1, output: 5, cacheRead: 0.1, cacheWrite: 1.25 },
			contextWindow: 200000,
			maxTokens: 64000,
		} as const,
		"claude-haiku-4-5-20251001": {
			id: "claude-haiku-4-5-20251001",
			name: "Claude Haiku 4.5",
			api: "anthropic-messages",
			provider: "anthropic",
			baseUrl: "https://api.anthropic.com",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 1, output: 5, cacheRead: 0.1, cacheWrite: 1.25 },
			contextWindow: 200000,
			maxTokens: 64000,
		} as const,
		"claude-sonnet-4-5": {
			id: "claude-sonnet-4-5",
			name: "Claude Sonnet 4.5 (latest)",
			api: "anthropic-messages",
			provider: "anthropic",
			baseUrl: "https://api.anthropic.com",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 },
			contextWindow: 200000,
			maxTokens: 64000,
		} as const,
		"claude-sonnet-4-5-20250929": {
			id: "claude-sonnet-4-5-20250929",
			name: "Claude Sonnet 4.5",
			api: "anthropic-messages",
			provider: "anthropic",
			baseUrl: "https://api.anthropic.com",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 },
			contextWindow: 200000,
			maxTokens: 64000,
		} as const,
		"claude-sonnet-4-6": {
			id: "claude-sonnet-4-6",
			name: "Claude Sonnet 4.6",
			api: "anthropic-messages",
			provider: "anthropic",
			baseUrl: "https://api.anthropic.com",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 3, output: 15, cacheRead: 0.3, cacheWrite: 3.75 },
			contextWindow: 200000,
			maxTokens: 64000,
		} as const,
		"claude-opus-4-5": {
			id: "claude-opus-4-5",
			name: "Claude Opus 4.5 (latest)",
			api: "anthropic-messages",
			provider: "anthropic",
			baseUrl: "https://api.anthropic.com",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
			contextWindow: 200000,
			maxTokens: 64000,
		} as const,
		"claude-opus-4-5-20251101": {
			id: "claude-opus-4-5-20251101",
			name: "Claude Opus 4.5",
			api: "anthropic-messages",
			provider: "anthropic",
			baseUrl: "https://api.anthropic.com",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
			contextWindow: 200000,
			maxTokens: 64000,
		} as const,
		"claude-opus-4-6": {
			id: "claude-opus-4-6",
			name: "Claude Opus 4.6",
			api: "anthropic-messages",
			provider: "anthropic",
			baseUrl: "https://api.anthropic.com",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 5, output: 25, cacheRead: 0.5, cacheWrite: 6.25 },
			contextWindow: 200000,
			maxTokens: 128000,
		} as const,
	},
	"openai": {
		"gpt-4o": {
			id: "gpt-4o",
			name: "GPT-4o",
			api: "openai-responses",
			provider: "openai",
			baseUrl: "https://api.openai.com/v1",
			reasoning: false,
			input: ["text", "image"],
			cost: { input: 2.5, output: 10, cacheRead: 1.25, cacheWrite: 0 },
			contextWindow: 128000,
			maxTokens: 16384,
		} as const,
		"gpt-4o-mini": {
			id: "gpt-4o-mini",
			name: "GPT-4o mini",
			api: "openai-responses",
			provider: "openai",
			baseUrl: "https://api.openai.com/v1",
			reasoning: false,
			input: ["text", "image"],
			cost: { input: 0.15, output: 0.6, cacheRead: 0.08, cacheWrite: 0 },
			contextWindow: 128000,
			maxTokens: 16384,
		} as const,
		"gpt-4.1": {
			id: "gpt-4.1",
			name: "GPT-4.1",
			api: "openai-responses",
			provider: "openai",
			baseUrl: "https://api.openai.com/v1",
			reasoning: false,
			input: ["text", "image"],
			cost: { input: 2, output: 8, cacheRead: 0.5, cacheWrite: 0 },
			contextWindow: 1047576,
			maxTokens: 32768,
		} as const,
		"gpt-4.1-mini": {
			id: "gpt-4.1-mini",
			name: "GPT-4.1 mini",
			api: "openai-responses",
			provider: "openai",
			baseUrl: "https://api.openai.com/v1",
			reasoning: false,
			input: ["text", "image"],
			cost: { input: 0.4, output: 1.6, cacheRead: 0.1, cacheWrite: 0 },
			contextWindow: 1047576,
			maxTokens: 32768,
		} as const,
		"gpt-4.1-nano": {
			id: "gpt-4.1-nano",
			name: "GPT-4.1 nano",
			api: "openai-responses",
			provider: "openai",
			baseUrl: "https://api.openai.com/v1",
			reasoning: false,
			input: ["text", "image"],
			cost: { input: 0.1, output: 0.4, cacheRead: 0.03, cacheWrite: 0 },
			contextWindow: 1047576,
			maxTokens: 32768,
		} as const,
		"o3": {
			id: "o3",
			name: "o3",
			api: "openai-responses",
			provider: "openai",
			baseUrl: "https://api.openai.com/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 2, output: 8, cacheRead: 0.5, cacheWrite: 0 },
			contextWindow: 200000,
			maxTokens: 100000,
		} as const,
		"o3-mini": {
			id: "o3-mini",
			name: "o3-mini",
			api: "openai-responses",
			provider: "openai",
			baseUrl: "https://api.openai.com/v1",
			reasoning: true,
			input: ["text"],
			cost: { input: 1.1, output: 4.4, cacheRead: 0.55, cacheWrite: 0 },
			contextWindow: 200000,
			maxTokens: 100000,
		} as const,
		"o4-mini": {
			id: "o4-mini",
			name: "o4-mini",
			api: "openai-responses",
			provider: "openai",
			baseUrl: "https://api.openai.com/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 1.1, output: 4.4, cacheRead: 0.28, cacheWrite: 0 },
			contextWindow: 200000,
			maxTokens: 100000,
		} as const,
		"gpt-5": {
			id: "gpt-5",
			name: "GPT-5",
			api: "openai-responses",
			provider: "openai",
			baseUrl: "https://api.openai.com/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 1.25, output: 10, cacheRead: 0.125, cacheWrite: 0 },
			contextWindow: 400000,
			maxTokens: 128000,
		} as const,
		"gpt-5-mini": {
			id: "gpt-5-mini",
			name: "GPT-5 Mini",
			api: "openai-responses",
			provider: "openai",
			baseUrl: "https://api.openai.com/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 0.25, output: 2, cacheRead: 0.025, cacheWrite: 0 },
			contextWindow: 400000,
			maxTokens: 128000,
		} as const,
		"gpt-5.2": {
			id: "gpt-5.2",
			name: "GPT-5.2",
			api: "openai-responses",
			provider: "openai",
			baseUrl: "https://api.openai.com/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 1.75, output: 14, cacheRead: 0.175, cacheWrite: 0 },
			contextWindow: 400000,
			maxTokens: 128000,
		} as const,
		"gpt-5.3-codex": {
			id: "gpt-5.3-codex",
			name: "GPT-5.3 Codex",
			api: "openai-responses",
			provider: "openai",
			baseUrl: "https://api.openai.com/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 1.75, output: 14, cacheRead: 0.175, cacheWrite: 0 },
			contextWindow: 400000,
			maxTokens: 128000,
		} as const,
		"gpt-5.4": {
			id: "gpt-5.4",
			name: "GPT-5.4",
			api: "openai-responses",
			provider: "openai",
			baseUrl: "https://api.openai.com/v1",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 2.5, output: 15, cacheRead: 0.25, cacheWrite: 0 },
			contextWindow: 1050000,
			maxTokens: 128000,
		} as const,
		"codex-mini-latest": {
			id: "codex-mini-latest",
			name: "Codex Mini",
			api: "openai-responses",
			provider: "openai",
			baseUrl: "https://api.openai.com/v1",
			reasoning: true,
			input: ["text"],
			cost: { input: 1.5, output: 6, cacheRead: 0.375, cacheWrite: 0 },
			contextWindow: 200000,
			maxTokens: 100000,
		} as const,
	},
	"google": {
		"gemini-2.0-flash": {
			id: "gemini-2.0-flash",
			name: "Gemini 2.0 Flash",
			api: "google-generative-ai",
			provider: "google",
			baseUrl: "https://generativelanguage.googleapis.com/v1beta",
			reasoning: false,
			input: ["text", "image"],
			cost: { input: 0.1, output: 0.4, cacheRead: 0.025, cacheWrite: 0 },
			contextWindow: 1048576,
			maxTokens: 8192,
		} as const,
		"gemini-2.5-flash": {
			id: "gemini-2.5-flash",
			name: "Gemini 2.5 Flash",
			api: "google-generative-ai",
			provider: "google",
			baseUrl: "https://generativelanguage.googleapis.com/v1beta",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 0.3, output: 2.5, cacheRead: 0.075, cacheWrite: 0 },
			contextWindow: 1048576,
			maxTokens: 65536,
		} as const,
		"gemini-2.5-pro": {
			id: "gemini-2.5-pro",
			name: "Gemini 2.5 Pro",
			api: "google-generative-ai",
			provider: "google",
			baseUrl: "https://generativelanguage.googleapis.com/v1beta",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 1.25, output: 10, cacheRead: 0.31, cacheWrite: 0 },
			contextWindow: 1048576,
			maxTokens: 65536,
		} as const,
		"gemini-3-flash-preview": {
			id: "gemini-3-flash-preview",
			name: "Gemini 3 Flash Preview",
			api: "google-generative-ai",
			provider: "google",
			baseUrl: "https://generativelanguage.googleapis.com/v1beta",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 0.5, output: 3, cacheRead: 0.05, cacheWrite: 0 },
			contextWindow: 1048576,
			maxTokens: 65536,
		} as const,
		"gemini-3-pro-preview": {
			id: "gemini-3-pro-preview",
			name: "Gemini 3 Pro Preview",
			api: "google-generative-ai",
			provider: "google",
			baseUrl: "https://generativelanguage.googleapis.com/v1beta",
			reasoning: true,
			input: ["text", "image"],
			cost: { input: 2, output: 12, cacheRead: 0.2, cacheWrite: 0 },
			contextWindow: 1000000,
			maxTokens: 64000,
		} as const,
	},
	"zai": {
		"glm-5": {
			id: "glm-5",
			name: "GLM-5",
			api: "anthropic-messages",
			provider: "zai",
			baseUrl: "",
			reasoning: true,
			input: ["text"],
			cost: { input: 1.0, output: 3.2, cacheRead: 0.1, cacheWrite: 0 },
			contextWindow: 200000,
			maxTokens: 128000,
		} as const,
		"glm-4.7": {
			id: "glm-4.7",
			name: "GLM-4.7",
			api: "anthropic-messages",
			provider: "zai",
			baseUrl: "",
			reasoning: true,
			input: ["text"],
			cost: { input: 0.55, output: 2.2, cacheRead: 0.06, cacheWrite: 0 },
			contextWindow: 200000,
			maxTokens: 128000,
		} as const,
	},
	"minimax": {
		"MiniMax-M2.5": {
			id: "MiniMax-M2.5",
			name: "MiniMax M2.5",
			api: "anthropic-messages",
			provider: "minimax",
			baseUrl: "",
			reasoning: true,
			input: ["text"],
			cost: { input: 0.3, output: 1.2, cacheRead: 0.03, cacheWrite: 0 },
			contextWindow: 200000,
			maxTokens: 128000,
		} as const,
		"MiniMax-M2.1": {
			id: "MiniMax-M2.1",
			name: "MiniMax M2.1",
			api: "anthropic-messages",
			provider: "minimax",
			baseUrl: "",
			reasoning: true,
			input: ["text"],
			cost: { input: 0.3, output: 1.2, cacheRead: 0.03, cacheWrite: 0 },
			contextWindow: 200000,
			maxTokens: 128000,
		} as const,
	},
	"minimax-cn": {
		"MiniMax-M2.5": {
			id: "MiniMax-M2.5",
			name: "MiniMax M2.5",
			api: "anthropic-messages",
			provider: "minimax-cn",
			baseUrl: "",
			reasoning: true,
			input: ["text"],
			cost: { input: 0.29, output: 1.15, cacheRead: 0.03, cacheWrite: 0 },
			contextWindow: 200000,
			maxTokens: 128000,
		} as const,
		"MiniMax-M2.1": {
			id: "MiniMax-M2.1",
			name: "MiniMax M2.1",
			api: "anthropic-messages",
			provider: "minimax-cn",
			baseUrl: "",
			reasoning: true,
			input: ["text"],
			cost: { input: 0.29, output: 1.15, cacheRead: 0.03, cacheWrite: 0 },
			contextWindow: 200000,
			maxTokens: 128000,
		} as const,
	},
	"kimi-coding": {
		"kimi-for-coding": {
			id: "kimi-for-coding",
			name: "Kimi For Coding",
			api: "anthropic-messages",
			provider: "kimi-coding",
			baseUrl: "",
			reasoning: true,
			input: ["text"],
			cost: { input: 0.6, output: 2.5, cacheRead: 0.06, cacheWrite: 0 },
			contextWindow: 262144,
			maxTokens: 8192,
		} as const,
	},
} as const;
