import OpenAI from 'openai';
import type { Responses } from 'openai/resources/responses/responses';
import type {
  ProviderAdapter,
  ProviderRequest,
  ProviderMessage,
  ProviderToolDef,
  ProviderUserContent,
  ProviderAssistantContent,
  NormalizedStreamEvent,
} from '@shared/provider-types';
import type { StopReason } from '@shared/types';
import {
  THINKING_LEVEL_TO_REASONING_EFFORT,
  filterBlockedHeaders,
} from '@shared/constants';

// ---------------------------------------------------------------------------
// Thinking level → Response API reasoning effort mapping
// ---------------------------------------------------------------------------

type ReasoningEffort = 'low' | 'medium' | 'high';

function mapReasoningEffort(level: string): ReasoningEffort | undefined {
  const mapped = THINKING_LEVEL_TO_REASONING_EFFORT[level];
  if (!mapped) return undefined;
  // Responses API only supports low/medium/high; clamp xhigh to high
  if (mapped === 'xhigh') return 'high';
  return mapped as ReasoningEffort;
}

// ---------------------------------------------------------------------------
// Message conversion: ProviderMessage[] -> ResponseInputItem[]
// ---------------------------------------------------------------------------

function toResponseInput(
  messages: ProviderMessage[],
): Responses.ResponseInputItem[] {
  const result: Responses.ResponseInputItem[] = [];

  for (const msg of messages) {
    if (msg.role === 'user') {
      // Separate tool_result blocks from regular content
      const regularContent: ProviderUserContent[] = [];
      const toolResults: Extract<ProviderUserContent, { type: 'tool_result' }>[] = [];

      for (const block of msg.content) {
        if (block.type === 'tool_result') {
          toolResults.push(block);
        } else {
          regularContent.push(block);
        }
      }

      // Emit function_call_output items for tool results
      for (const tr of toolResults) {
        result.push({
          type: 'function_call_output',
          call_id: tr.toolUseId,
          output: tr.output,
        });
      }

      // Emit user message with remaining content (if any)
      if (regularContent.length > 0) {
        const textParts = regularContent
          .filter((b): b is Extract<ProviderUserContent, { type: 'text' }> => b.type === 'text')
          .map(b => b.text);

        if (textParts.length > 0) {
          result.push({
            role: 'user',
            content: textParts.join('\n'),
          });
        }
      }
    } else {
      // assistant
      const textParts: string[] = [];
      const functionCalls: Responses.ResponseFunctionToolCall[] = [];

      for (const block of msg.content as ProviderAssistantContent[]) {
        switch (block.type) {
          case 'text':
            textParts.push(block.text);
            break;
          case 'thinking':
            // Reasoning is generated by the API, skip in input
            break;
          case 'tool_use':
            functionCalls.push({
              type: 'function_call',
              call_id: block.id,
              name: block.name,
              arguments: JSON.stringify(block.input),
            });
            break;
          case 'server_tool_use':
          case 'server_tool_result':
            // Anthropic server tool blocks — skip for OpenAI
            break;
        }
      }

      // Emit assistant message if there's text content
      if (textParts.length > 0) {
        result.push({
          role: 'assistant',
          content: textParts.join(''),
        });
      }

      // Emit function_call items
      for (const fc of functionCalls) {
        result.push(fc);
      }
    }
  }

  return result;
}

// ---------------------------------------------------------------------------
// Tool conversion: ProviderToolDef[] -> FunctionTool[]
// ---------------------------------------------------------------------------

function toResponseTools(
  tools: ProviderToolDef[],
): Responses.FunctionTool[] {
  return tools.map(
    (t): Responses.FunctionTool => ({
      type: 'function',
      name: t.name,
      description: t.description,
      parameters: t.inputSchema,
      strict: false,
    }),
  );
}

// ---------------------------------------------------------------------------
// Adapter
// ---------------------------------------------------------------------------

export class OpenAIResponsesAdapter implements ProviderAdapter {
  readonly id: string;
  private client: OpenAI;

  constructor(apiKey: string, baseUrl?: string, id?: string) {
    this.id = id ?? 'openai-responses';
    this.client = new OpenAI({
      apiKey,
      ...(baseUrl ? { baseURL: baseUrl } : {}),
    });
  }

  async *stream(
    request: ProviderRequest,
  ): AsyncGenerator<NormalizedStreamEvent> {
    // Internal state to synthesize NormalizedStreamEvent lifecycle
    let messageStarted = false;
    let nextBlockIndex = 0;

    // Map: output_index → our block index (for tracking output items)
    const outputBlockIndices = new Map<number, number>();
    // Map: output_index/content_index key → our block index (for text blocks within messages)
    const contentBlockIndices = new Map<string, number>();
    // Track which reasoning items have been started (by output_index)
    const startedReasoningBlocks = new Set<number>();
    // Track which function call items have been started (by output_index)
    const startedFunctionCallBlocks = new Set<number>();
    // Track whether we have any function_call output items (for stop reason)
    let hasFunctionCalls = false;

    try {
      const input = toResponseInput(request.messages);

      // --- Build params ---
      const maxTokens = request.maxTokens ?? 16_000;

      // Determine reasoning configuration from thinkingLevel
      let reasoning: { effort: ReasoningEffort; summary: 'auto' } | undefined;
      if (request.thinkingLevel && request.thinkingLevel !== 'off') {
        const effort = mapReasoningEffort(request.thinkingLevel);
        if (effort) {
          reasoning = { effort, summary: 'auto' };
        }
      } else if (request.thinkingBudget && request.thinkingBudget > 0) {
        // Fallback: legacy thinkingBudget path
        let effort: ReasoningEffort = 'medium';
        if (request.thinkingBudget <= 1024) {
          effort = 'low';
        } else if (request.thinkingBudget >= 32000) {
          effort = 'high';
        }
        reasoning = { effort, summary: 'auto' };
      }

      const tools = request.tools && request.tools.length > 0
        ? toResponseTools(request.tools)
        : undefined;

      const responseParams: Record<string, unknown> = {
        model: request.model,
        input,
        ...(request.systemPrompt ? { instructions: request.systemPrompt } : {}),
        ...(tools ? { tools } : {}),
        ...(maxTokens ? { max_output_tokens: maxTokens } : {}),
        ...(reasoning ? { reasoning } : {}),
        store: false,
      };

      // extraParams override (highest priority)
      if (request.extraParams) {
        Object.assign(responseParams, request.extraParams);
      }

      // customHeaders injection
      const safeHeaders = filterBlockedHeaders(request.customHeaders);

      const response = await this.client.responses.stream(
        responseParams as Parameters<typeof this.client.responses.stream>[0],
        {
          signal: request.signal ?? undefined,
          ...(safeHeaders ? { headers: safeHeaders } : {}),
        },
      );

      for await (const event of response) {
        // Emit message_start on first event
        if (!messageStarted) {
          messageStarted = true;
          yield { type: 'message_start' };
        }

        switch (event.type) {
          // ---- Output item lifecycle ----

          case 'response.output_item.added': {
            const item = event.item;
            const outputIndex = event.output_index;

            if (item.type === 'reasoning') {
              // Start a thinking block
              const blockIndex = nextBlockIndex++;
              outputBlockIndices.set(outputIndex, blockIndex);
              startedReasoningBlocks.add(outputIndex);
              yield {
                type: 'content_block_start',
                index: blockIndex,
                block: { type: 'thinking' },
              };
            } else if (item.type === 'function_call') {
              // Start a tool_use block
              hasFunctionCalls = true;
              const blockIndex = nextBlockIndex++;
              outputBlockIndices.set(outputIndex, blockIndex);
              startedFunctionCallBlocks.add(outputIndex);
              yield {
                type: 'content_block_start',
                index: blockIndex,
                block: {
                  type: 'tool_use',
                  id: item.call_id,
                  name: item.name,
                },
              };
            }
            // For 'message' type, we wait for content_part.added to start text blocks
            break;
          }

          case 'response.output_item.done': {
            const outputIndex = event.output_index;
            const item = event.item;

            if (item.type === 'reasoning' && startedReasoningBlocks.has(outputIndex)) {
              const blockIndex = outputBlockIndices.get(outputIndex);
              if (blockIndex !== undefined) {
                yield { type: 'content_block_stop', index: blockIndex };
              }
            } else if (item.type === 'function_call' && startedFunctionCallBlocks.has(outputIndex)) {
              const blockIndex = outputBlockIndices.get(outputIndex);
              if (blockIndex !== undefined) {
                yield { type: 'content_block_stop', index: blockIndex };
              }
            }
            break;
          }

          // ---- Content part lifecycle (within message output items) ----

          case 'response.content_part.added': {
            const part = event.part;
            if (part.type === 'output_text') {
              const key = `${event.output_index}:${event.content_index}`;
              const blockIndex = nextBlockIndex++;
              contentBlockIndices.set(key, blockIndex);
              yield {
                type: 'content_block_start',
                index: blockIndex,
                block: { type: 'text' },
              };
            }
            break;
          }

          case 'response.content_part.done': {
            const key = `${event.output_index}:${event.content_index}`;
            const blockIndex = contentBlockIndices.get(key);
            if (blockIndex !== undefined) {
              yield { type: 'content_block_stop', index: blockIndex };
            }
            break;
          }

          // ---- Streaming deltas ----

          case 'response.output_text.delta': {
            const key = `${event.output_index}:${event.content_index}`;
            const blockIndex = contentBlockIndices.get(key);
            if (blockIndex !== undefined) {
              yield {
                type: 'content_block_delta',
                index: blockIndex,
                delta: { type: 'text_delta', text: event.delta },
              };
            }
            break;
          }

          case 'response.function_call_arguments.delta': {
            const blockIndex = outputBlockIndices.get(event.output_index);
            if (blockIndex !== undefined) {
              yield {
                type: 'content_block_delta',
                index: blockIndex,
                delta: { type: 'input_json_delta', partialJson: event.delta },
              };
            }
            break;
          }

          case 'response.reasoning_text.delta': {
            const blockIndex = outputBlockIndices.get(event.output_index);
            if (blockIndex !== undefined) {
              yield {
                type: 'content_block_delta',
                index: blockIndex,
                delta: { type: 'thinking_delta', thinking: event.delta },
              };
            }
            break;
          }

          case 'response.reasoning_summary_text.delta': {
            // Map reasoning summary to thinking delta as well (fallback for models
            // that return summary instead of raw reasoning)
            const blockIndex = outputBlockIndices.get(event.output_index);
            if (blockIndex !== undefined) {
              yield {
                type: 'content_block_delta',
                index: blockIndex,
                delta: { type: 'thinking_delta', thinking: event.delta },
              };
            }
            break;
          }

          // ---- Response lifecycle ----

          case 'response.completed': {
            const resp = event.response;

            // Determine stop reason
            let stopReason: StopReason = 'end_turn';
            if (resp.status === 'incomplete') {
              stopReason = 'max_tokens';
            } else if (resp.status === 'failed') {
              stopReason = 'error';
            } else if (hasFunctionCalls) {
              stopReason = 'tool_use';
            }

            yield {
              type: 'message_delta',
              stopReason,
              usage: resp.usage
                ? {
                    inputTokens: resp.usage.input_tokens,
                    outputTokens: resp.usage.output_tokens,
                    cacheReadTokens: resp.usage.input_tokens_details?.cached_tokens ?? 0,
                    cacheWriteTokens: 0,
                  }
                : undefined,
            };

            yield { type: 'message_stop' };
            break;
          }

          case 'response.failed': {
            const resp = event.response;
            const errorMsg = resp.error?.message ?? 'Response failed';
            yield { type: 'error', error: new Error(errorMsg) };
            break;
          }

          case 'response.incomplete': {
            // Emit message_delta with max_tokens and close
            yield {
              type: 'message_delta',
              stopReason: 'max_tokens',
              usage: event.response.usage
                ? {
                    inputTokens: event.response.usage.input_tokens,
                    outputTokens: event.response.usage.output_tokens,
                    cacheReadTokens: event.response.usage.input_tokens_details?.cached_tokens ?? 0,
                    cacheWriteTokens: 0,
                  }
                : undefined,
            };
            yield { type: 'message_stop' };
            break;
          }

          // Ignore other events (audio, web_search, file_search, code_interpreter, etc.)
          default:
            break;
        }
      }
    } catch (err: unknown) {
      // Abort signals should not be treated as errors
      if (err instanceof Error && err.name === 'AbortError') {
        return;
      }
      const error = err instanceof Error ? err : new Error(String(err));
      yield { type: 'error', error };
    }
  }
}
